### ISSUE TITLE
Arquivos de estilos 

### ISSUE THREAD

**Issue by Franppires** [masthiago/nthashtagfinder#13]
Temos o arquivo de estilo global que contem informações de reset da pagina e o tipo da font e um index de css que está a família da font que pode estar se conflitando, segue print

![image](https://user-images.githubusercontent.com/104803568/236870588-a1363aea-5eef-4542-b251-9cc84d87bd4b.png)
![image](https://user-images.githubusercontent.com/104803568/236870680-41e83d2d-ab82-4d4b-afee-ad794b25abb8.png)

**Comment by masthiago** [comment]
O Component `GlobalStyle` foi retirado e o arquivo `src/components/Home/globalStyle.jsx` será retirado em uma commit futuro, mas optou-se por usar reset.css e index.css para configurações Globais. #16
